export const vendors = [
  { name: 'Dominion', category: 'grocery' },
  { name: 'Sobeys', category: 'grocery' },
  { name: 'PC Express', category: 'grocery' },
  { name: 'Shoppers', category: 'grocery' },
  { name: 'Mushrooms', category: 'grocery' },
  { name: 'ATLANTIC SUPERS', category: 'grocery' },
  { name: 'Colemans', category: 'grocery' },
  { name: 'COSTCO GAS W132', category: 'gas' },
  { name: 'Costco', category: 'grocery' },
  { name: 'COSTCO WHOLESAL', category: 'grocery' },
  { name: 'Greenfarm', category: 'grocery' },
  { name: 'Powells', category: 'grocery' },
  { name: 'Burdens', category: 'grocery' },
  { name: 'Small Point General Store', category: 'grocery' },
  { name: 'Swiss Chalet', category: 'restaurants' },
  { name: 'Moxie', category: 'restaurants' },
  { name: 'terre', category: 'restaurants' },
  { name: 'Jungle Jims', category: 'restaurants' },
  { name: 'Thai Express', category: 'restaurants' },
  { name: 'Saucy Mouth', category: 'restaurants' },
  { name: 'Curry Delight', category: 'restaurants' },
  { name: 'Quesada', category: 'restaurants' },
  { name: 'sushi', category: 'restaurants' },
  { name: 'Pizza', category: 'restaurants' },
  { name: 'Cojones', category: 'restaurants' },
  { name: 'Mary Brown', category: 'restaurants' },
  { name: 'MaryBrown', category: 'restaurants' },
  { name: 'McDonalds', category: 'restaurants' },
  { name: 'Gahan', category: 'restaurants' },
  { name: 'Coldwater', category: 'restaurants' },
  { name: 'landwash', category: 'restaurants' },
  { name: 'Smokes', category: 'restaurants' },
  { name: 'Starbucks', category: 'restaurants' },
  { name: 'Meineke', category: 'cars' },
  { name: 'Apple', category: 'computers' },
  { name: 'Netflix', category: 'internet' },
  { name: 'privateinternetaccess', category: 'internet' },
  { name: 'Backblaze', category: 'internet' },
  { name: 'Disney Plus', category: 'internet' },
  { name: 'DigitalOcean', category: 'internet' },
  { name: 'Halifax Herald', category: 'internet' },
  { name: 'Spotify', category: 'internet' },
  { name: 'Linode', category: 'internet' },
  { name: 'Hey Email', category: 'internet' },
  { name: 'Stratechery', category: 'internet' },
  { name: 'Hover', category: 'internet' },
  { name: 'NYT', category: 'internet' },
  { name: 'Petsmart', category: 'pets' },
  { name: 'Critters', category: 'pets' },
  { name: 'Wags to Whisker', category: 'pets' },
  { name: 'Pet City', category: 'pets' },
  { name: 'Borderfree', category: 'clothes' },
  { name: 'North Atlantic', category: 'gas' },
  { name: 'Irving', category: 'gas' },
  { name: 'Atlantic Petroleum', category: 'gas' },
  { name: 'Topsail Road Esso', category: 'gas' },
  { name: 'CIRCLE K', category: 'gas' },
  { name: 'Dollarama', category: 'dollar Store' },
  { name: 'Only Deals', category: 'dollar Store' },
  { name: 'Telus', category: 'monthly' },
  { name: 'Bell Aliant', category: 'monthly' },
  { name: 'Newfoundland Power', category: 'monthly' },
  { name: 'aircanada', category: 'travel' },
  { name: 'marine atlantic', category: 'travel' },
  { name: 'jema', category: 'travel' },
  { name: 'veterinary', category: 'pets' },
  { name: 'pup town', category: 'pets' },
  { name: 'trupanion', category: 'pets' },
  { name: 'KNIGHTS OF COLUMBUS', category: 'insurance' },
  { name: 'manulife', category: 'insurance' },
  { name: 'nlc', category: 'liquor' },
  { name: 'mcdonald', category: 'restaurants' },
  { name: 'kfc', category: 'restaurants' },
  { name: 'quidi vidi brewing', category: 'restaurants' },
  { name: 'BK #103382', category: 'restaurants' },
  { name: 'gingergrass', category: 'restaurants' },
  { name: 'bannerman brewing', category: 'restaurants' },
  { name: "coleman's", category: 'grocery' },
  { name: 'pet valu', category: 'pets' },
  { name: 'East side', category: 'restaurants' },
  { name: "The big's", category: 'restaurants' },
  { name: 'Magic wok', category: 'restaurants' },
  { name: 'burrito', category: 'restaurants' },
  { name: 'dairy queen', category: 'restaurants' },
  { name: 'Tim hortons', category: 'restaurants' },
  { name: 'Subway', category: 'restaurants' },
  { name: 'freshii', category: 'restaurants' },
  { name: 'Electronic Funds Transfer PREAUTHORIZED DEBIT LN', category: 'cars' },
  { name: 'Steffen', category: 'monthly' },
  { name: 'blue on water', category: 'restaurants' },
]
