import Nav from '@/components/nav'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Source_Code_Pro } from 'next/font/google'
import './globals.css'
import Footer from './footer'
import { cn } from '@/lib/shadcn-utils'

const inter = Inter({ subsets: ['latin'] })
const SourceCodePro = Source_Code_Pro({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn('bg-stone-100 dark:bg-stone-900 text-blue-800', SourceCodePro.className)}>
        <main className="container mx-auto mt-24 max-w-6xl flex gap-12 align-top">
          <Nav />
          <div className="w-full">
            {children}
            <Footer />
          </div>
        </main>
      </body>
    </html>
  )
}
